/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jwrap.boot;

import java.util.Base64;

public class App {
	public static void main(String[] args) {
		for (int i = 0; i < args.length; i++) {
			System.out.println(args[i]);
			switch (args[i]) {
			case "--jar":
				System.out.println(parseStringArg(args[i+1]));
				i++;
				break;
			case "--main":
				System.out.println(parseStringArg(args[i+1]));
				i++;
				break;
			case "--args":
				System.out.println(String.join(",", parseStringArrayArg(args[i+1])));
				i++;
				break;
			}
		}
	}
	private static String parseStringArg(String base64)
	{
	    byte[] decodedBytes = Base64.getDecoder().decode(base64);
	    return new String(decodedBytes);
	}
	private static String[] parseStringArrayArg(String base64List)
	{
		String[] args = base64List.split(",");
		String[] result = new String[args.length];
		for (int i=0; i<args.length; i++)
		{
			result[i] = parseStringArg(args[i]);
		}
		return result;
	}
}
